#ifndef GAMEDEFINES_H
#define GAMEDEFINES_H
#define WORLDSCALE 10
#define TILESIZE 10

enum CellState {EMPTY=0, ALIVE, SOLID};
enum TileType {NORMNEIGH, DIANEIGH, STRAIGHTNEIGH};
enum SpecialEffect {NONE=0, MOVUP, MOVRIGHT, MOVDOWN, MOVLEFT};
enum WrapMode {USEOFFMAP, MIRROR, WRAP};

#endif