#ifndef GAMEDEFINES_H
#define GAMEDEFINES_H
#define WORLDSCALE 10
#define TILESIZE 10
#define MAXBOARDSIZE 512

enum State {EMPTY=0, ALIVE, SOLID};
enum TileType {NORMNEIGH, DIANEIGH, STRAIGHTNEIGH};
enum SpecialEffect {NONE=0, MOVUP, MOVRIGHT, MOVDOWN, MOVLEFT, AIR};
enum WrapMode {USEOFFMAP, MIRROR, WRAP};
enum EventType { CRASH=0, CREATION, DELETION, PASSTHROUGH, SLOWDOWN, SPEEDUP };

#endif